###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: 8080,8081,8082,8083
  mode: debug  # debug;release
  gorm:
    LogMode: false # db log
  view:
    limit: 10 
  
ethereum:
  # chainID: 12759
  # host: http://localhost:8540
  chainID: 1
  host: https://mainnet.infura.io/1UoO4I
  passphrase: tDydrX7ia8Zx6Vwr  # rand

