
###health
GET http://127.0.0.1:8080/health
Content-Type: application/json

{
}

###DeployObj
POST http://127.0.0.1:8080/obj/deploy
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111"
}

###ModifyObjValue
POST http://127.0.0.1:8080/obj/set
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "address":"0xcc0084fd6c095de69290655a1d45188c8348d1fc",
    "value":"就是在奎罗斯位于里外不是人"
}

###RawModifyObjValue
POST http://127.0.0.1:8080/obj/rawset
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "address":"0xcc0084fd6c095de69290655a1d45188c8348d1fc",
    "value":"世界杯B组末轮争夺，葡萄牙对阵伊朗下半场补时第1分钟，伊朗人安萨里法德干净利落的罚进点球"
}

###GetObjValue
GET http://127.0.0.1:8080/obj/get/0xcc0084fd6c095de69290655a1d45188c8348d1fc
Content-Type: application/json

{
}
