
###health
GET http://127.0.0.1:8080/health
Content-Type: application/json

{
}

###DeployCallObj
POST http://127.0.0.1:8080/callobj/deploy
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111"
}

###ModifyCallObjValue
POST http://127.0.0.1:8080/callobj/set
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "address":"0xede4a2ebfdc250a72c180de433bde42ce2585080",
    "call_address":"0xdd0ed37821a6220a315f59b399e20b9a2ef58c58",
    "value":"{\"value\":\"就是在奎罗斯位于里外不是\"}"
}