
###health
GET http://127.0.0.1:8080/health
Content-Type: application/json

{
}

###DeployObj
POST http://127.0.0.1:8080/tipjar/deploy
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111"
}

###DepositTipJar
POST http://127.0.0.1:8080/tipjar/deposit
Content-Type: application/json

{
    "address":"0x3f04b7967463ed5046150563419b9617a7e468b3",
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "amount":"20",
    "decimals":"18",
    "iswait":"true"
}

###GetTipJarBalance
GET http://127.0.0.1:8080/tipjar/balance/0x3f04b7967463ed5046150563419b9617a7e468b3
Content-Type: application/json

{
}
