
###health
GET http://127.0.0.1:8080/health
Content-Type: application/json

{
}

###DeployInfo
POST http://127.0.0.1:8080/info/deploy
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111"
}

###SetInfoChannel
POST http://127.0.0.1:8080/info/set_channel
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "address":"0xd1ae8046c80a9ec0f9fa76ebcb0fb2ae89bc666b",
    "value":"20180705"
}

###GetInfoChannel
GET http://127.0.0.1:8080/info/get_channel/0xd1ae8046c80a9ec0f9fa76ebcb0fb2ae89bc666b
Content-Type: application/json

{
}

###SetInfo
POST http://127.0.0.1:8080/info/set
Content-Type: application/json

{
    "from":"0x762009cd5dcabb5a125008d70f5efdbdff2aa782",
    "pwd":"a11111",
    "address":"0xd1ae8046c80a9ec0f9fa76ebcb0fb2ae89bc666b",
    "name":"培华",
    "value":"46"
}

###GetInfo
GET http://127.0.0.1:8080/info/get/0xd1ae8046c80a9ec0f9fa76ebcb0fb2ae89bc666b
Content-Type: application/json

{
}
