
###health
GET http://127.0.0.1:8080/health
Content-Type: application/json

{
}

###CreateAccount /account/create/:passphrase
POST http://localhost:8080/account/create/a11111
Content-Type: application/json

{
}

###CreateBIP39 /account/bip39/create
POST http://localhost:8080/account/bip39/create
Content-Type: application/json

{
    "mnemonic":"况 居 调 单 习 嘛 虚 诗 奥 待 罐 寒",
    "path":"m/44'/60'/0'/0/0"
}

###CreateBIP39Keysore /account/bip39/keystore/create
POST http://localhost:8080/account/bip39/keystore/create
Content-Type: application/json

{
    "mnemonic":"况 居 调 单 习 嘛 虚 诗 奥 待 罐 寒",
    "path":"m/44'/60'/0'/0/0",
    "pwd":"a11111"
}

###CreateAccount /account/checkpwd/:addr/:passphrase
POST http://localhost:8080/account/checkpwd/0x0b74d6c3ea2696047af5f1f45616340d1e94b1c7/123
Content-Type: application/json

{
}